# SwitchOptions
# Included when DUSK_PLATFORM_SWITCH=ON

set(DUSK_PLATFORM_SWITCH ON CACHE BOOL "" FORCE)

set(DUSK_ENABLE_CODE_MODS OFF CACHE BOOL "" FORCE)
set(DUSK_HAS_FUNCHOOK OFF CACHE INTERNAL "" FORCE)
set(DUSK_HAS_PREPATCH OFF CACHE INTERNAL "" FORCE)
set(DUSK_GFX_DEBUG_GROUPS OFF CACHE BOOL "" FORCE)

add_compile_definitions(
    SQLITE_OS_UNIX=1
    SQLITE_OMIT_WAL=1
    SQLITE_OMIT_LOAD_EXTENSION=1
)

set(BOREALIS_ENABLE_SENTRY OFF CACHE BOOL "" FORCE)
set(BOREALIS_ENABLE_DISCORD OFF CACHE BOOL "" FORCE)
set(BOREALIS_ENABLE_UPDATE OFF CACHE BOOL "" FORCE)
set(BOREALIS_ENABLE_CRASH OFF CACHE BOOL "" FORCE)
set(BOREALIS_ENABLE_NET OFF CACHE BOOL "" FORCE)
set(BOREALIS_ENABLE_WEBSOCKET OFF CACHE BOOL "" FORCE)
set(BOREALIS_ENABLE_DATA OFF CACHE BOOL "" FORCE)
set(BOREALIS_ENABLE_IO OFF CACHE BOOL "" FORCE)
set(BOREALIS_ENABLE_FILE_SELECT OFF CACHE BOOL "" FORCE)
set(BOREALIS_ENABLE_DISC OFF CACHE BOOL "" FORCE)
set(BOREALIS_ENABLE_HTTP OFF CACHE BOOL "" FORCE)

set(AURORA_ENABLE_DVD OFF CACHE BOOL "No nod/Rust DVD backend on Switch; native shim instead" FORCE)
set(AURORA_ENABLE_RMLUI ON CACHE BOOL "RmlUi menus/overlays on Switch (freetype from portlibs or vendored)" FORCE)

include(${CMAKE_CURRENT_LIST_DIR}/SwitchDeps.cmake)

add_compile_definitions(DUSK_PLATFORM_SWITCH=1 TARGET_SWITCH=1 VK_USE_PLATFORM_VI_NN)

set(DUSK_SWITCH_OPT_FLAGS
  -O3
  -ffunction-sections
  -fdata-sections
  -fomit-frame-pointer
  -fno-math-errno
  -fno-trapping-math
)
